spring.application.name=Serialization-Deserialization-ApiValidation

#spring.datasource.url=jdbc:postgresql://localhost:5432/serialization_deserialization_apiValidation
#spring.datasource.username=postgres
#spring.datasource.password=1234
#
#spring.jpa.hibernate.ddl-auto=update
#spring.datasource.driver-class-name=org.postgresql.Driver

# --------------- not needed ---------------------------------
#spring.jackson.default-property-inclusion=non_null
#spring.jackson.date-format=yyyy-MM-dd

# ----------------------- it's for ht -------------------------
spring.datasource.url=jdbc:h2:mem:stateless_security
spring.datasource.username=sa
spring.datasource.password=

